GITHUB: "https://github.com/zhengxiaowai"
LINKED: "https://cn.linkedin.com/in/seanho116"
EMAIL: "h1x2y3awalm@gmail.com"
COPYRIGHT: "Copyright SeanHo 2016"
ALIYUN: "https://promotion.aliyun.com/ntms/act/ambassador/sharetouser.html?userCode=yzwl15as"
QINIU: "https://portal.qiniu.com/signup?code=3llwj9hl21tn6"
DJANGO: "https://www.djangoproject.com/"
